### ISSUE TITLE
Gurman's critique

### ISSUE THREAD

**Issue by GurmanToor** [WedelFelix/WedelFelix.github.io#1]
* Prerequisites: Can provide sample resume (just link to your own resume.md file)
* Try to keep steps to one instruction per step
* Steps should begin with action verbs
* Steps should be as concise as possible to avoid confusing user
* Step 2, Step 3: Note should be on separate line 
* I like the use of animated gifs
* I like the options that you give the user on how to add your resume to the site. Both options have animated gifs which show user how they look, nice touch
* Lots of resources which is good

**Comment by WedelFelix** [comment]
Thank you for your feedback, I have made the recommended changes.

**Comment by WedelFelix** [comment]
Thank you for your feedback, I have made the recommended changes.
